---
title: LSU Phoenix Alumni
timezone: UTC
collections:
  announcements:
    title: Announcements
    output: false
  events:
    title: Events
    output: true
  pages:
    title: Pages
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
baseurl: "/"
port: 4000
exclude:
- README.md
sass:
  style: compressed
gems:
- jekyll-paginate
paginate: 5
