---
title: LSU Phoenix Alumni
timezone: UTC
collections:
  announcements:
    title: Announcements
    output: false
  board_members:
    title: Board Members
    output: false
  events:
    title: Events
    output: true
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  photos:
    title: Photos
    output: false
markdown: kramdown
baseurl: "/"
port: 4000
exclude:
- README.md
sass:
  style: compressed
